name: Zip UI Bundle with Gulp
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Generate UI Bundle
        run: node_modules/.bin/gulp bundle
      - name: Generate tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UIBundle_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: build/ui-bundle.zip
      - name: Trigger Pages Workflow
        run: |
          curl --request POST 'https://api.github.com/repos/Napfschnecke/inspectit-ocelot/actions/workflows/publish.yml/dispatches' \
          --header 'Authorization: Bearer ${{ secrets.PAT }}' \
          --header 'Content-Type: application/json'  \
          --data-raw '{
            "ref":"concept/ascii-ssg-pages"
            }'
